### ISSUE TITLE
Update db failed on slug

### ISSUE THREAD

**Issue by hiddenman** [netbox-community/Device-Type-Library-Import#40]
1. Updated to the latest version
2. Removed the "repo" directory (due to the https://github.com/minitriga/Netbox-Device-Type-Library-Import/issues/38)
3. Ran the script.
4. Got these errors:
`Manufacturer Exists: A10 - 2
Manufacturer Exists: APC - 3
Manufacturer Exists: ActionTec - 4
Manufacturer Exists: Adtran - 5
Manufacturer Exists: Alcatel-Lucent - 6
Manufacturer Exists: Allied Telesis - 7
Manufacturer Exists: Alpha - 8
Manufacturer Exists: Arista - 9
Manufacturer Exists: Aruba - 10
Manufacturer Exists: Avocent - 11
Manufacturer Exists: Brocade - 12
Manufacturer Exists: Cisco - 13
Manufacturer Exists: Citrix - 14
Manufacturer Exists: CyberPower - 15
Manufacturer Exists: Deciso - 16
Manufacturer Exists: Dell - 17
Manufacturer Exists: Delta - 18
Manufacturer Exists: Eaton - 19
Manufacturer Exists: Extreme Networks - 20
Manufacturer Exists: F5 - 21
Manufacturer Exists: FS - 22
Manufacturer Exists: Factor-TS - 23
Manufacturer Exists: Fortinet - 1
Manufacturer Exists: Generic - 24
Manufacturer Exists: HPE - 25
Manufacturer Exists: Huawei - 26
Manufacturer Exists: Infinera - 27
Manufacturer Exists: Infoblox - 28
Manufacturer Exists: Infotecs - 29
Manufacturer Exists: Juniper - 30
Manufacturer Exists: Mellanox - 32
Manufacturer Exists: MikroTik - 33
Manufacturer Exists: NetApp - 34
Manufacturer Exists: Netonix - 35
Manufacturer Exists: Nokia - 36
Manufacturer Exists: Opengear - 37
Manufacturer Exists: Palo Alto - 38
Manufacturer Exists: Panduit - 39
Manufacturer Exists: QNAP - 40
Manufacturer Exists: Raritan - 41
Manufacturer Exists: Raspberry Pi - 42
Manufacturer Exists: Riverbed - 43
Manufacturer Exists: Rockwell Automation - 44
Manufacturer Exists: Solid Optics - 45
Manufacturer Exists: TP-Link - 46
Manufacturer Exists: Testing - 47
Manufacturer Exists: TrendNet - 48
Manufacturer Exists: TrippLite - 49
Manufacturer Exists: Ubiquiti - 50
Manufacturer Exists: Vertiv - 51
Manufacturer Exists: WTI - 52
Manufacturer Exists: ZPE - 53

[{},{},{},{},{"slug":["manufacturer with this slug already exists."]},{},{},{},{},{},{}]

{"manufacturer":["Related object not found using the provided attributes: {'name': '3Com', 'slug': '3com'}"]}
Traceback (most recent call last):
  File "/opt/netbox/Netbox-Device-Type-Library-Import/./nb-dt-import.py", line 446, in <module>
    main()
  File "/opt/netbox/Netbox-Device-Type-Library-Import/./nb-dt-import.py", line 436, in main
    createDeviceTypes(deviceTypes, nb)
  File "/opt/netbox/Netbox-Device-Type-Library-Import/./nb-dt-import.py", line 352, in createDeviceTypes
    dt.id, nb)
UnboundLocalError: local variable 'dt' referenced before assignment
`

**Comment by hiddenman** [comment]
I manually added 3Com manufacturer and this helped.
So it looks like the update process does not add new manufacturers.

**Comment by danner26** [comment]
Hello @hiddenman, the NetBox Community will be taking over this repository. Due to the fact that this issue has been around for a very long time and we have updated the requirements within this repository as well as the new codebase for NetBox and DeviceType-Library, I am going to close it. Should you encounter any further issues, please feel free to contact us. Thank you!
