### ISSUE TITLE
The request failed with code 400 Bad Request

### ISSUE THREAD

**Issue by rvigne** [netbox-community/Device-Type-Library-Import#55]
Hi everyone,

I have a problem when i use teh script. I have an error message :
![image](https://user-images.githubusercontent.com/113897830/191471158-02d02d2b-338c-4b18-8930-b5a0c9d89333.png)

I use Netbox v3.3.2

**Comment by ndom91** [comment]
Can you provide some more information? Including the full error / stack trace?

**Comment by rvigne** [comment]
Hello,

Thank you for your help and sorry to take a long time to answer...
I found what is the problem, and i solved this.

But i have another problem now...
![image](https://user-images.githubusercontent.com/113897830/200187097-a128a290-1ba9-4f09-863a-2a756194266f.png)

I have this and my .env is configured like this :
![image](https://user-images.githubusercontent.com/113897830/200187148-fa3c1c01-b673-4aee-a358-88eaaceec3d1.png)

Thank you for your answer ;)

**Comment by danner26** [comment]
I am glad to hear you solved this @rvigne, I am going to close this issue now. If you have any further concerns, please do not hesitate to reach out.
