### ISSUE TITLE
Rasberry Pi not importing on scan

### ISSUE THREAD

**Issue by spastro** [netbox-community/Device-Type-Library-Import#57]
Anyone know why my rasberry pi 3B+ devices are not being recognised when scanning with netbox-device-discovery? 
I have PC, Printers currenty adding correctly as my base test. 

Any way i can troubleshoot?

**Comment by ndom91** [comment]
This is not `netbox-device-discovery`. Maybe try opening an issue in their repo?

**Comment by spastro** [comment]
Good point, instead how do i stop the script skipping the device if it was not recognised?

I see this in the python script 

 if not recognized_device:
                log.info('Failed to recognize the device, skipped')
                continue

Can i just hash it out like this 

 if not 
#recognized_device:
              #  log.info('Failed to recognize the device, skipped')
                continue

Cheers

**Comment by spastro** [comment]
cheers!
