### ISSUE TITLE
SSL self signed certificate issue

### ISSUE THREAD

**Issue by ait0rn00b** [netbox-community/Device-Type-Library-Import#58]
Yeah the same error as always, but I have changed bot options to false in settings.py and still get the following error:
![image](https://user-images.githubusercontent.com/74489662/198404074-2f5a7e5a-6be3-457c-bfa1-1c82a1bf87a1.png)

I know is a very recurring error but I'm a bit lost, netbox 3.3.5

**Comment by ait0rn00b** [comment]
I also tried with the env but nothing works, forgot to mention it

**Comment by BryceTech122** [comment]
Im having this same issue with self signed certs and with the env set to true and false

**Comment by hermeticsoup** [comment]
Same issue here; fresh install using lae.netbox ansible role on Ubuntu 20.04 with nginx in front of it.

I used: 

`os.environ['REQUESTS_CA_BUNDLE'] = '/path/to/your/ca.pem' #or .crt`

to resolve. Worked a treat. Thanks for that!

**Comment by danner26** [comment]
Hey @ait0rn00b, @BMeach, @dmidlo and @hermeticsoup. I have implemented a fix that will solve this SSL issue. Now, when you utilize the `IGNORE_SSL_ERRORS=True` definition, the library will properly ignore the SSL errors and initialize the API connection. This causes the library to A) suppress the SSL verification warning messages, and B) allow the API transaction to be successful. If you ever require more verbosity, you can also use the `--verbose` flag which will show you the raised exception. Note: the `--verbose` flag is new and will be further implemented throughout the library when possible
