### ISSUE TITLE
 The request failed with code 503 Service Temporarily Unavailable but more specific details were not returned in json. Check the NetBox Logs or investigate this exception's error attribute.

### ISSUE THREAD

**Issue by XyroDev** [netbox-community/Device-Type-Library-Import#65]
i get this error in both ways of installing it.
![image](https://user-images.githubusercontent.com/108021842/217122418-f7cbeacc-3573-428d-ba3d-d075cbdf1699.png)

**Comment by ndom91** [comment]
This points to an error on Netbox's side (server side). As the error message states, there should be more details in your Netbox logs. See your Docker container's logs or [here](https://docs.netbox.dev/en/stable/configuration/system/#logging) if you're running it without docker.

**Comment by danner26** [comment]
Hello @XyroDev, as @ndom91 this issue is localized to your NetBox instance and is not related to this repository. For the time being I am going to close this issue, but if you have any further concerns please do not hesitate to reach out
