### ISSUE TITLE
IGNORE_SSL_ERRORS not propigating

### ISSUE THREAD

**Issue by CodexMafia** [netbox-community/Device-Type-Library-Import#95]
Hi -- I tried running the importer on my instance of Netbox and I ran into issues where when I set the IGNORE_SSL_ERRORS to 'True' it was not propagating all the way.  The resolution to this was to set line 481 in netbox_api.py to the below.

```
response = requests.patch(url, headers=headers, files=files, verify=False)
``` 

_What was added was ', verify=False'_

This just needs to take the propagation from the .env file to fix. Thanks!

**Comment by danner26** [comment]
Thank you for this. This also assisted us in catching an issue with permissions that we did not know about previously.
